services:
  app:
    container_name: task_container
    build: .
    depends_on:
      - databaseImage
    ports:
      - "3000:3000"
    env_file:
      - ./.env  

  databaseImage:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"    