version: "3.8"

services:
  app:
    container_name: task_container
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - ./.env  
    networks:
      - my_network  
    volumes:
      - .:/app  
    command: ["sh", "-c", "npx prisma migrate deploy && npm start"]  

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"  
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d crm_contact_db"]
      interval: 5s
      retries: 5
      start_period: 10s

networks:
  my_network:
    driver: bridge          
